export const mockCards = [
  {
    id: "1",
    name: "黑蓮花",
    nameEn: "Black Lotus",
    set: "Alpha Edition",
    setCode: "LEA",
    type: "tcg" as const,
    game: "MTG",
    rarity: "特稀有",
    rarityColor: "#FFD700",
    price: 2800000,
    priceChange: 5.2,
    image: "https://via.placeholder.com/200x280/1a1a2e/gold?text=Black+Lotus",
    condition: "NM",
    description: "魔法風雲會最稀有的卡牌之一，被稱為「神話中的神話」。",
    tags: ["Power 9", "Alpha", "限定"],
  },
  {
    id: "2",
    name: "超夢",
    nameEn: "Mewtwo",
    set: "基礎版 第一彈",
    setCode: "BS1",
    type: "tcg" as const,
    game: "寶可夢",
    rarity: "全圖閃卡",
    rarityColor: "#E040FB",
    price: 45000,
    priceChange: -1.8,
    image: "https://via.placeholder.com/200x280/1a1a2e/purple?text=Mewtwo",
    condition: "PSA 10",
    description: "1996年第一彈基礎版全圖超夢，PSA 10 品相。",
    tags: ["PSA 10", "1st Edition", "基礎版"],
  },
  {
    id: "3",
    name: "青眼白龍",
    nameEn: "Blue-Eyes White Dragon",
    set: "初期版",
    setCode: "SDK",
    type: "tcg" as const,
    game: "遊戲王",
    rarity: "超稀有",
    rarityColor: "#00BCD4",
    price: 120000,
    priceChange: 8.5,
    image: "https://via.placeholder.com/200x280/1a1a2e/cyan?text=Blue+Eyes",
    condition: "LP",
    description: "初代遊戲王最具代表性的卡牌，收藏市場長年熱門。",
    tags: ["初期版", "海馬", "傳說"],
  },
  {
    id: "4",
    name: "LeBron James RC",
    nameEn: "LeBron James Rookie Card",
    set: "2003-04 Topps Chrome",
    setCode: "TPC03",
    type: "sports" as const,
    game: "NBA",
    rarity: "Refractor",
    rarityColor: "#FF6B35",
    price: 380000,
    priceChange: 12.3,
    image: "https://via.placeholder.com/200x280/1a1a2e/orange?text=LeBron+RC",
    condition: "BGS 9.5",
    description: "LeBron James 2003年新秀年 Topps Chrome Refractor，BGS 9.5 極品。",
    tags: ["Rookie", "BGS 9.5", "Refractor"],
  },
  {
    id: "5",
    name: "Mike Trout 1/1",
    nameEn: "Mike Trout Auto Patch 1/1",
    set: "2011 Bowman Sterling",
    setCode: "BS11",
    type: "sports" as const,
    game: "MLB",
    rarity: "1/1 Superfractor",
    rarityColor: "#FF1744",
    price: 5200000,
    priceChange: 2.1,
    image: "https://via.placeholder.com/200x280/1a1a2e/red?text=Trout+1%2F1",
    condition: "PSA 10",
    description: "Mike Trout 簽名球衣卡 1/1 Superfractor，全球唯一一張。",
    tags: ["1/1", "Auto", "Patch", "Superfractor"],
  },
  {
    id: "6",
    name: "閃電黑比卡超",
    nameEn: "Pikachu Illustrator",
    set: "CoroCoro 限定",
    setCode: "PROMO",
    type: "tcg" as const,
    game: "寶可夢",
    rarity: "Promo 限定",
    rarityColor: "#FFCA28",
    price: 9500000,
    priceChange: 25.0,
    image: "https://via.placeholder.com/200x280/1a1a2e/yellow?text=Pikachu+Illus.",
    condition: "PSA 10",
    description: "世界上最稀有的寶可夢卡牌之一，僅39張存在於世。",
    tags: ["PSA 10", "限定", "世界最貴"],
  },
];

export const mockPosts = [
  {
    id: "1",
    type: "showcase",
    board: "MTG",
    title: "開箱！Final Fantasy MTG 聯名系列整盒，拉到了超夢幻閃卡",
    author: { name: "龍騎士_Kai", avatar: "K", reputation: 1520 },
    content: "剛剛開了一整盒 FF 聯名，結果運氣爆炸好...",
    upvotes: 342,
    comments: 87,
    views: 4821,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    tags: ["開箱", "FF聯名", "閃卡"],
    image: true,
  },
  {
    id: "2",
    type: "price_check",
    board: "NBA",
    title: "價格詢問｜Wembanyama 2023 Rookie PSA 10，現在行情大概多少？",
    author: { name: "球卡獵人", avatar: "B", reputation: 830 },
    content: "剛入手一張 Wemby 新秀卡打算送鑑定，想先了解 PSA 10 的行情...",
    upvotes: 58,
    comments: 23,
    views: 1243,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    tags: ["價格詢問", "Wembanyama", "PSA"],
    image: false,
  },
  {
    id: "3",
    type: "discussion",
    board: "寶可夢",
    title: "【討論】近期寶可夢市場大幅下跌，大家怎麼看待現在的入場時機？",
    author: { name: "Poké_Collector", avatar: "P", reputation: 2340 },
    content: "觀察了一下最近幾個月的成交紀錄，整體跌幅大約 15-20%...",
    upvotes: 215,
    comments: 156,
    views: 8932,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    tags: ["市場分析", "投資", "趨勢"],
    image: false,
  },
  {
    id: "4",
    type: "news",
    board: "遊戲王",
    title: "【資訊】Master Duel 新系列確認實體化，神之宣告將再版！",
    author: { name: "決鬥王", avatar: "D", reputation: 4120 },
    content: "官方今天公佈了下一個實體卡系列，多張人氣禁卡確認解禁...",
    upvotes: 891,
    comments: 234,
    views: 15673,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    tags: ["官方資訊", "再版", "禁卡表"],
    image: false,
  },
  {
    id: "5",
    type: "showcase",
    board: "MLB",
    title: "分享我的 Shohei Ohtani 完整 RC 收藏，花了三年才湊齊",
    author: { name: "大谷應援團", avatar: "O", reputation: 3760 },
    content: "從 2018 年開始收集大谷翔平的新秀卡，終於在今年把主要 RC 都補齊了...",
    upvotes: 1203,
    comments: 318,
    views: 22451,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    tags: ["展示", "大谷", "完整收藏"],
    image: true,
  },
];

export const mockPriceHistory = [
  { date: "1月", price: 340000 },
  { date: "2月", price: 355000 },
  { date: "3月", price: 348000 },
  { date: "4月", price: 362000 },
  { date: "5月", price: 375000 },
  { date: "6月", price: 380000 },
];

export const mockUsers = [
  { id: "1", name: "龍騎士_Kai", avatar: "K", reputation: 1520, cards: 247, posts: 89 },
  { id: "2", name: "Poké_Collector", avatar: "P", reputation: 2340, cards: 1832, posts: 156 },
  { id: "3", name: "決鬥王", avatar: "D", reputation: 4120, cards: 956, posts: 412 },
  { id: "4", name: "大谷應援團", avatar: "O", reputation: 3760, cards: 543, posts: 203 },
  { id: "5", name: "球卡獵人", avatar: "B", reputation: 830, cards: 128, posts: 47 },
];

export const boards = [
  { id: "all", label: "全部", icon: "🃏", count: 1234 },
  { id: "mtg", label: "MTG", icon: "⚔️", count: 342 },
  { id: "pokemon", label: "寶可夢", icon: "⚡", count: 567 },
  { id: "yugioh", label: "遊戲王", icon: "🌀", count: 289 },
  { id: "nba", label: "NBA", icon: "🏀", count: 198 },
  { id: "mlb", label: "MLB", icon: "⚾", count: 145 },
  { id: "nfl", label: "NFL", icon: "🏈", count: 87 },
];
